title: Sohyeon Kim
show_downloads: False
google_analytics:
  id: G-5TGFXQ6NVJ
theme: jekyll-theme-minimal
url: https://sohyeonkim.github.io
branch: master
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
